package gui;

import javax.swing.JOptionPane;

import exceptions.FacadeException;
import facadedb.AdminFacadeDB;
import servicebeans.Company;

public class AddCompany extends javax.swing.JFrame {
/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
private AdminFacadeDB admin;
    /**
     * Creates new form AddCompany
     */
private javax.swing.JButton cancel;
private javax.swing.JLabel compName;
private javax.swing.JLabel compPass;
private javax.swing.JLabel compPass1;
private javax.swing.JTextField email;
private javax.swing.JTextField name;
private javax.swing.JButton okBtn;
private javax.swing.JTextField password;
private static AddCompany addCompany;
public static AddCompany  getAddCompany(AdminFacadeDB admin){
	if (addCompany==null) {
		return addCompany=new  AddCompany(admin) ;
	}
	else {
		addCompany.dispose();
		return addCompany=new  AddCompany(admin) ;
	}
}
    private AddCompany(AdminFacadeDB admin) {
    	super("Add Company");
    	this.admin=admin;
    	try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddCompany.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddCompany.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddCompany.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddCompany.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        initComponents();
        setLocation(500,280);
        setVisible(true);
        setDefaultCloseOperation(EXIT_ON_CLOSE);
   }

   /**
    * This method is called from within the constructor to initialize the form.
    * WARNING: Do NOT modify this code. The content of this method is always
    * regenerated by the Form Editor.
    */
   
   // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
   private void initComponents() {

       compName = new javax.swing.JLabel();
       compPass = new javax.swing.JLabel();
       compPass1 = new javax.swing.JLabel();
       name = new javax.swing.JTextField();
       password = new javax.swing.JTextField();
       email = new javax.swing.JTextField();
       okBtn = new javax.swing.JButton();
       cancel = new javax.swing.JButton();

       setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

       compName.setText("Company name :");

       compPass.setText("Password :");

       compPass1.setText("Email :");

       okBtn.setText("Ok");
       okBtn.addActionListener(new java.awt.event.ActionListener() {
           public void actionPerformed(java.awt.event.ActionEvent evt) {
               okBtnActionPerformed(evt);
           }
       });

       cancel.setText("Cancel");
       cancel.addActionListener(new java.awt.event.ActionListener() {
           public void actionPerformed(java.awt.event.ActionEvent evt) {
               cancelActionPerformed(evt);
           }
       });

       javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
       getContentPane().setLayout(layout);
       layout.setHorizontalGroup(
           layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
           .addGroup(layout.createSequentialGroup()
               .addGap(30, 30, 30)
               .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                   .addComponent(compName)
                   .addComponent(compPass)
                   .addComponent(compPass1))
               .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
               .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                   .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                   .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                   .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
               .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
           .addGroup(layout.createSequentialGroup()
               .addGap(86, 86, 86)
               .addComponent(okBtn)
               .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 94, Short.MAX_VALUE)
               .addComponent(cancel)
               .addGap(40, 40, 40))
       );
       layout.setVerticalGroup(
           layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
           .addGroup(layout.createSequentialGroup()
               .addGap(49, 49, 49)
               .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                   .addComponent(compName)
                   .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
               .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
               .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                   .addComponent(compPass)
                   .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
               .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
               .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                   .addComponent(compPass1)
                   .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
               .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
               .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                   .addComponent(okBtn)
                   .addComponent(cancel))
               .addContainerGap())
       );

       pack();
   }// </editor-fold>                        

   private void okBtnActionPerformed(java.awt.event.ActionEvent evt) {                                      
       String thename=name.getText();
       String thePassword=password.getText();
       String theEmail=email.getText();
       if (!thename.equals("")&&!thePassword.equals("")&&isValidEmailAddress(theEmail)) {
		try {
			admin.creatCompany(new Company(0, thename, thePassword, theEmail));
			dispose();
		} catch (FacadeException e) {
			new ErrorHandle().showEventDemo(e.getMessage());  
		}
	}
		else {
			JOptionPane.showMessageDialog(null, "Wrong Username / Password/Email");
			name.setText("");
			password.setText("");
			email.setText("");
			name.requestFocus();
		}
	}                        

   private void cancelActionPerformed(java.awt.event.ActionEvent evt) {                                       
       dispose();
   }    
   public boolean isValidEmailAddress(String email) {
       String ePattern = "^[a-zA-Z0-9.!#$%&'*+/=?^_`{|}~-]+@((\\[[0-9]{1,3}\\.[0-9]{1,3}\\.[0-9]{1,3}\\.[0-9]{1,3}\\])|(([a-zA-Z\\-0-9]+\\.)+[a-zA-Z]{2,}))$";
       java.util.regex.Pattern p = java.util.regex.Pattern.compile(ePattern);
       java.util.regex.Matcher m = p.matcher(email);
       return m.matches();
}
 
}

