package gui;


import javax.swing.JOptionPane;

import exceptions.FacadeException;
import facadedb.AdminFacadeDB;
import servicebeans.Customer;

public class AddCustomer extends javax.swing.JFrame {
/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
private AdminFacadeDB admin;
private javax.swing.JButton cancel;
private javax.swing.JLabel compName;
private javax.swing.JLabel compPass;
private javax.swing.JLabel jLabel1;
private javax.swing.JTextField name;
	private javax.swing.JButton okBtn;
	private javax.swing.JTextField password;
	private static AddCustomer addCustomer;

	public static AddCustomer getAddCustomer(AdminFacadeDB admin) {
		if (addCustomer == null) {
			return addCustomer = new AddCustomer(admin);
		} else {
			addCustomer.dispose();
			return addCustomer = new AddCustomer(admin);
		}

	}

	private AddCustomer(AdminFacadeDB admin) {
		super("Add Customer");
	this.admin=admin;
	   try {
	       for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
	           if ("Nimbus".equals(info.getName())) {
	               javax.swing.UIManager.setLookAndFeel(info.getClassName());
	               break;
	           }
	       }
	   } catch (ClassNotFoundException ex) {
	       java.util.logging.Logger.getLogger(AddCompany.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	   } catch (InstantiationException ex) {
	       java.util.logging.Logger.getLogger(AddCompany.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	   } catch (IllegalAccessException ex) {
	       java.util.logging.Logger.getLogger(AddCompany.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	   } catch (javax.swing.UnsupportedLookAndFeelException ex) {
	       java.util.logging.Logger.getLogger(AddCompany.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	   }
    initComponents();
    setLocationRelativeTo(null);
    setVisible(true);
}

/**
* This method is called from within the constructor to initialize the form.
* WARNING: Do NOT modify this code. The content of this method is always
* regenerated by the Form Editor.
*/
// <editor-fold defaultstate="collapsed" desc="Generated Code">                          
private void initComponents() {

   compName = new javax.swing.JLabel();
   compPass = new javax.swing.JLabel();
   name = new javax.swing.JTextField();
   password = new javax.swing.JTextField();
   okBtn = new javax.swing.JButton();
   cancel = new javax.swing.JButton();
   jLabel1 = new javax.swing.JLabel();

   setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

   compName.setText("Customer name :");

   compPass.setText("Password :");

   okBtn.setText("Ok");
   okBtn.addActionListener(new java.awt.event.ActionListener() {
       public void actionPerformed(java.awt.event.ActionEvent evt) {
           okBtnActionPerformed(evt);
       }
   });

   cancel.setText("Cancel");
   cancel.addActionListener(new java.awt.event.ActionListener() {
       public void actionPerformed(java.awt.event.ActionEvent evt) {
           cancelActionPerformed(evt);
       }
   });

   jLabel1.setText("Add New Customer");

   javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
   getContentPane().setLayout(layout);
   layout.setHorizontalGroup(
       layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
       .addGroup(layout.createSequentialGroup()
           .addGap(86, 86, 86)
           .addComponent(okBtn)
           .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 94, Short.MAX_VALUE)
           .addComponent(cancel)
           .addGap(40, 40, 40))
       .addGroup(layout.createSequentialGroup()
           .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(layout.createSequentialGroup()
                   .addGap(30, 30, 30)
                   .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                       .addComponent(compName)
                       .addComponent(compPass))
                   .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                   .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                       .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                       .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
               .addGroup(layout.createSequentialGroup()
                   .addGap(86, 86, 86)
                   .addComponent(jLabel1)))
           .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
   );
   layout.setVerticalGroup(
       layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
       .addGroup(layout.createSequentialGroup()
           .addGap(17, 17, 17)
           .addComponent(jLabel1)
           .addGap(18, 18, 18)
           .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(compName)
               .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
           .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
           .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(compPass)
               .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
           .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
           .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(okBtn)
               .addComponent(cancel))
           .addContainerGap())
   );

   pack();
}// </editor-fold>                        

private void okBtnActionPerformed(java.awt.event.ActionEvent evt) {                                      
	String thename=name.getText();
    String thePassword=password.getText();
    if (!thename.equals("")&&!thePassword.equals("")) {
		try {
			admin.creatCustomer(new Customer(0, thename, thePassword));
			dispose();
		} catch (FacadeException e) {
			new ErrorHandle().showEventDemo(e.getMessage());  
		}
	}
		else {
			JOptionPane.showMessageDialog(null, "bad Username / Password");
			name.setText("");
			password.setText("");
			name.requestFocus();
		}
}                                     

private void cancelActionPerformed(java.awt.event.ActionEvent evt) {                                       
  dispose();
}
                                


// Variables declaration - do not modify                     

// End of variables declaration                   
}


