package gui;

import java.sql.Timestamp;

import exceptions.ErrorType;
import exceptions.FacadeException;
import facadedb.CompanyFacadeDB;
import servicebeans.Coupon;
import servicebeans.CouponType;

public class AddCoupon extends javax.swing.JFrame {
    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	// Variables declaration - do not modify                     
    private javax.swing.JTextField amount;
    private javax.swing.JButton cancel;
    private javax.swing.JLabel compName;
    private javax.swing.JLabel compName1;
    private javax.swing.JLabel compName2;
    private javax.swing.JLabel compPass;
    private javax.swing.JLabel compPass1;
    private javax.swing.JLabel compPass2;
    private javax.swing.JLabel compPass3;
    private javax.swing.JLabel compPass6;
    private javax.swing.JList<String> couponTypes;
    private javax.swing.JTextField endDate;
    private javax.swing.JTextField endDate1;
    private javax.swing.JTextField endDate2;
    private javax.swing.JTextField imgPath;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea massage;
    private javax.swing.JButton okBtn;
    private javax.swing.JTextField price;
    private javax.swing.JTextField startDate;
    private javax.swing.JTextField startDate1;
    private javax.swing.JTextField startDate2;
    private javax.swing.JTextField title;
    private CompanyFacadeDB company;
    // End of variables declaration           
    /**
     * Creates new form AddCompany
     */
	private static AddCoupon addCoupon;

	public static AddCoupon getAddCoupon(CompanyFacadeDB company) {
		if (addCoupon == null) {
			return addCoupon = new AddCoupon(company);
		} else {
			addCoupon.dispose();
			return addCoupon = new AddCoupon(company);
		}

	}
    private AddCoupon(CompanyFacadeDB company) {
    	super("Add Coupon");
    	this.company=company;
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddCoupon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddCoupon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddCoupon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddCoupon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        initComponents();
         setLocationRelativeTo(null);
         setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        compName = new javax.swing.JLabel();
        compPass = new javax.swing.JLabel();
        title = new javax.swing.JTextField();
        startDate = new javax.swing.JTextField();
        okBtn = new javax.swing.JButton();
        cancel = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        endDate = new javax.swing.JTextField();
        compPass1 = new javax.swing.JLabel();
        amount = new javax.swing.JTextField();
        compPass2 = new javax.swing.JLabel();
        compName1 = new javax.swing.JLabel();
        compPass3 = new javax.swing.JLabel();
        price = new javax.swing.JTextField();
        compName2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        couponTypes = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        massage = new javax.swing.JTextArea();
        compPass6 = new javax.swing.JLabel();
        imgPath = new javax.swing.JTextField();
        startDate1 = new javax.swing.JTextField();
        startDate2 = new javax.swing.JTextField();
        endDate1 = new javax.swing.JTextField();
        endDate2 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setLocation(new java.awt.Point(0, 0));

        compName.setText("Coupon title :");

        compPass.setText("Start Date :");

        startDate.setText("Day");

        okBtn.setText("Ok");
        okBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okBtnActionPerformed(evt);
            }
        });

        cancel.setText("Cancel");
        cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelActionPerformed(evt);
            }
        });

        jLabel1.setText("Add New Coupon");

        endDate.setText("Day");

        compPass1.setText("End Date :");

        compPass2.setText("Massage:");

        compName1.setText("Amount :");

        compPass3.setText("Type");

        compName2.setText("Price :");

        couponTypes.setModel(new javax.swing.AbstractListModel<String>() {
    		/**
    		 * 
    		 */
    		private static final long serialVersionUID = 1L;
    		String[] strings = { String.valueOf(CouponType.CAMPING),
    				String.valueOf(CouponType.ELECTRICITY), String.valueOf(CouponType.FOOD),
    				String.valueOf(CouponType.HEALTH), String.valueOf(CouponType.RESTURANTS),
    				String.valueOf(CouponType.SPORTS), String.valueOf(CouponType.TRAVELING) };

            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(couponTypes);

        massage.setColumns(20);
        massage.setRows(5);
        jScrollPane2.setViewportView(massage);

        compPass6.setText("img path :");

        startDate1.setText("Month");
        startDate1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
            }
        });

        startDate2.setText("Year");

        endDate1.setText("Month");

        endDate2.setText("Year");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addComponent(okBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 97, Short.MAX_VALUE)
                .addComponent(cancel)
                .addGap(40, 40, 40))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(compName1)
                                    .addComponent(compPass3))
                                .addGap(34, 34, 34)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(amount, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(compPass2)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(compName)
                                    .addComponent(compPass1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(compPass)
                                .addGap(46, 46, 46)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(endDate, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(startDate, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(startDate1, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE)
                                    .addComponent(endDate1))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(endDate2)
                                    .addComponent(startDate2)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(compPass6, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(54, 54, 54)
                                .addComponent(imgPath, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(compName2, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(price, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGap(50, 50, 50))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(compName)
                    .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(compPass)
                    .addComponent(startDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(startDate1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(startDate2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(compPass1)
                    .addComponent(endDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(endDate1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(endDate2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(compName1)
                    .addComponent(amount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(compPass3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addGap(18, 18, 18)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(compPass2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(price, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(compName2))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(compPass6, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(imgPath, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(okBtn)
                    .addComponent(cancel))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>      

    private void okBtnActionPerformed(java.awt.event.ActionEvent evt) {
    	if (CompanyFrame.checkDate(endDate2, endDate1, endDate)
    			&&CompanyFrame.checkDate(startDate2, startDate1, startDate)) {
 		   String theTitle=title.getText();
      String startTime=startDate2.getText()+"-"+startDate1.getText()+"-"+startDate.getText()
      +" 00:00:00";
      System.out.println(startTime);
      Timestamp start = Timestamp.valueOf(startTime);
      String endTime=endDate2.getText()+"-"+endDate1.getText()+"-"+endDate.getText()
      +" 00:00:00";
      Timestamp end = Timestamp.valueOf(endTime);
 		int theAmount=Integer.valueOf(amount.getText()).intValue();
 		String theMassage=massage.getText();
 		double thePrice=Double.valueOf(price.getText()).doubleValue();
 		String img=imgPath.getText();
 		long id=0;
 	   if (!couponTypes.isSelectionEmpty() && couponTypes.getSelectedValue() != null&&
 			   theAmount>=0&&thePrice>=0&&!theTitle.equals("")&&!theMassage.equals("")&&!img.equals("")&&
 			   !startDate.getText().equals("")&&!endDate.getText().equals("")) {
 			CouponType type = CouponType.valueOf(couponTypes.getSelectedValue());
 			try {
 				company.creatCoupon(new Coupon(id, theTitle, start, end, theAmount, type, theMassage,
 						thePrice, img));
 				dispose();
 			} catch (FacadeException e) {
 				new ErrorHandle().showEventDemo(e.getMessage());  
 			}
 	   }
    	}
    	else{
    	      String startTime=startDate2.getText()+"-"+startDate1.getText()+"-"+startDate.getText()
    	      +" 00:00:00";
    	      System.out.println(startTime);
    		new ErrorHandle().showEventDemo(ErrorType.DATE_VALUES_INSERTED_ARE_NOT_VALID.toString());  
    	}
 	   
 		
    }                                     

    private void cancelActionPerformed(java.awt.event.ActionEvent evt) {                                       
       dispose();
    }                                



        
}