package musicPlay;

import java.io.File;

import javax.swing.JFrame;



import javafx.scene.media.Media;
import javafx.scene.media.MediaPlayer;


public class PlayMusic extends JFrame {
    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private javax.swing.JButton play;
    private javax.swing.JButton quit;
    private javax.swing.JButton stop;
    String bip = "songs"+File.separator+"coolSong.mp3";
    Media hit;
    MediaPlayer mediaPlayer;

        

public PlayMusic(){
	try {
		
		  new javafx.embed.swing.JFXPanel();
		    String uriString = new File(bip).toURI().toString();
		hit = new Media(uriString);
		mediaPlayer = new MediaPlayer(hit);
		 mediaPlayer.play();
        for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
            if ("Nimbus".equals(info.getName())) {
                javax.swing.UIManager.setLookAndFeel(info.getClassName());
                break;
            }
        }
    } catch (ClassNotFoundException ex) {
        java.util.logging.Logger.getLogger(PlayMusic.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
        java.util.logging.Logger.getLogger(PlayMusic.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
        java.util.logging.Logger.getLogger(PlayMusic.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
        java.util.logging.Logger.getLogger(PlayMusic.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	}
    initComponents();
    setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        play = new javax.swing.JButton();
        stop = new javax.swing.JButton();
        quit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        play.setText("Play");
        play.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playActionPerformed(evt);
            }
        });

        stop.setText("Stop");
        stop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stopActionPerformed(evt);
            }
        });

        quit.setText("Im so Lame quit music");
        quit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(quit)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(play)
                        .addGap(30, 30, 30)
                        .addComponent(stop)))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(stop)
                    .addComponent(play))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addComponent(quit)
                .addContainerGap())
        );
setLocationRelativeTo(null);
        pack();
    }// </editor-fold>                        

    private void playActionPerformed(java.awt.event.ActionEvent evt) {                                     
    	mediaPlayer.play();
    }                                    

    private void stopActionPerformed(java.awt.event.ActionEvent evt) {                                     
    	mediaPlayer.stop();
    }                                    

    private void quitActionPerformed(java.awt.event.ActionEvent evt) {
    	mediaPlayer.stop();
    	dispose();
    }                                    
               
}

